//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.User_Profile = new HashSet<User_Profile>();
        }
    
        public int login_ID { get; set; }
        public string login_username { get; set; }
        public string login_password { get; set; }
        public string login_random_string { get; set; }
        public bool login_approvalStatus { get; set; }
        public string User_Type_userType_ID { get; set; }
    
        public virtual User_Type User_Type { get; set; }
        public virtual ICollection<User_Profile> User_Profile { get; set; }
    }
}
