//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referee_Event_History
    {
        public int refEventHistory_ID { get; set; }
        public Nullable<int> refEventHistory_Total_Stars_Rating { get; set; }
        public int Sport_Event_event_ID { get; set; }
        public int User_Profile_Referee_Profile_ID { get; set; }
        public int User_Profile_School_Director_Profile_ID { get; set; }
        public string Referee_Status_refStatus_ID { get; set; }
        public int Sport_Type_Referees_sptTypeRef_ID { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
        public virtual Referee_Status Referee_Status { get; set; }
        public virtual User_Profile User_Profile1 { get; set; }
        public virtual Sport_Event Sport_Event { get; set; }
        public virtual Sport_Type_Referees Sport_Type_Referees { get; set; }
    }
}
