//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Sport_Event = new HashSet<Sport_Event>();
            this.Sport_Event1 = new HashSet<Sport_Event>();
        }
    
        public int sch_ID { get; set; }
        public string sch_Name { get; set; }
        public string sch_Street { get; set; }
        public string sch_City { get; set; }
        public string sch_State { get; set; }
        public string sch_Zip { get; set; }
        public string sch_Logo { get; set; }
        public int User_Profile_Director_Profile_ID { get; set; }
    
        public virtual ICollection<Sport_Event> Sport_Event { get; set; }
        public virtual ICollection<Sport_Event> Sport_Event1 { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
