//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_Name
    {
        public Sport_Name()
        {
            this.Sport_Event = new HashSet<Sport_Event>();
            this.Sport_Type_Referees = new HashSet<Sport_Type_Referees>();
            this.User_Profile_Referee = new HashSet<User_Profile_Referee>();
        }
    
        public int spt_Sport_Name_ID { get; set; }
        public string spt_Name { get; set; }
    
        public virtual ICollection<Sport_Event> Sport_Event { get; set; }
        public virtual ICollection<Sport_Type_Referees> Sport_Type_Referees { get; set; }
        public virtual ICollection<User_Profile_Referee> User_Profile_Referee { get; set; }
    }
}
