//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_Type_Referees
    {
        public Sport_Type_Referees()
        {
            this.Referee_Event_History = new HashSet<Referee_Event_History>();
        }
    
        public int sptTypeRef_ID { get; set; }
        public string sptTypeRef_Referee_Title { get; set; }
        public int Sport_Name_spt_Sport_Name_ID { get; set; }
    
        public virtual ICollection<Referee_Event_History> Referee_Event_History { get; set; }
        public virtual Sport_Name Sport_Name { get; set; }
    }
}
