//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StripeEntities : DbContext
    {
        public StripeEntities()
            : base("name=StripeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Referee_Event_History> Referee_Event_History { get; set; }
        public virtual DbSet<Referee_Status> Referee_Status { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Sport_Event> Sport_Event { get; set; }
        public virtual DbSet<Sport_Name> Sport_Name { get; set; }
        public virtual DbSet<Sport_Type_Referees> Sport_Type_Referees { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<User_Profile_Referee> User_Profile_Referee { get; set; }
    }
}
