//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile_Referee
    {
        public int ref_Game_Specialization_Type { get; set; }
        public int User_Profile_userProfile_ID { get; set; }
        public int Sport_Name_spt_Sport_Name_ID { get; set; }
    
        public virtual Sport_Name Sport_Name { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
