//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Type
    {
        public User_Type()
        {
            this.Logins = new HashSet<Login>();
        }
    
        public string userType_ID { get; set; }
        public string userType_Name { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
    }
}
