//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public User_Profile()
        {
            this.Referee_Event_History = new HashSet<Referee_Event_History>();
            this.Referee_Event_History1 = new HashSet<Referee_Event_History>();
            this.Schools = new HashSet<School>();
            this.User_Profile_Referee = new HashSet<User_Profile_Referee>();
        }
    
        public int userProfile_ID { get; set; }
        public string userProfile_First_Name { get; set; }
        public string userProfile_Last_Name { get; set; }
        public string userProfile_Email { get; set; }
        public string userProfile_Phone { get; set; }
        public string userProfile_Street { get; set; }
        public string userProfile_City { get; set; }
        public string userProfile_State { get; set; }
        public string userProfile_Zip { get; set; }
        public string userProfile_Photo { get; set; }
        public string userProfile_Background_Description { get; set; }
        public int Login_login_ID { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Referee_Event_History> Referee_Event_History { get; set; }
        public virtual ICollection<Referee_Event_History> Referee_Event_History1 { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<User_Profile_Referee> User_Profile_Referee { get; set; }
    }
}
